### ISSUE TITLE
Backend Crashes in Proxy Mode

### ISSUE THREAD

**Issue by tmess11** [antebrl/IPTV-Restream#44]
# Summary

Backend docker container occasionally randomly crashes when watching streams.

# Standard debugging steps

## How to reproduce?

1. Watch stream in Proxy mode (I've seen it happen 20 minutes in to 2 hours in)
2. Backend Crashes

## Expected behavior

Backend container continues to run after error. If it is a fatal error for the stream, pop an error up in the UI and make the user restart the stream or refresh. 

## Stacktrace

```
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: aborted
    at TLSSocket.socketCloseListener (node:_http_client:464:19)
    at TLSSocket.emit (node:events:530:35)
    at node:net:343:12
    at TCP.done (node:_tls_wrap:648:7)
Emitted 'error' event on Request instance at:
    at Request.onerror (node:internal/streams/readable:1028:14)
    at Request.emit (node:events:518:28)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1079:12)
    at IncomingMessage.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ECONNRESET'
}
```

# Other details

I have only seen this so far in Proxy mode, but not in restream mode.

**Comment by antebrl** [comment]
Thanks for the report!
Seems like a socket problem. Should also appear in any other streaming mode though.
I will look into it and fix it in a few days.

**Comment by antebrl** [comment]
I think I found the root cause and added error handling. That might have fixed it.
It's hard to test though. I streamed for several hours in proxy mode without any problems. But it might depend on the channel.

If you are encoutering any more crashes or a log-message like `Unhandled error:`, then please reopen this issue!

**Comment by tmess11** [comment]
Awesome! I will upgrade and test it as well. Yeah, it only happened a couple times over a few days of streaming. I will update if something happens.

**Comment by tmess11** [comment]
`Unhandled error: Error: aborted
    at TLSSocket.socketCloseListener (node:_http_client:464:19)
    at TLSSocket.emit (node:events:530:35)
    at node:net:343:12
    at TCP.done (node:_tls_wrap:648:7) {
  code: 'ECONNRESET'
}
node:_http_outgoing:655
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (node:_http_outgoing:655:11)
    at ServerResponse.header (/app/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/app/node_modules/express/lib/response.js:174:12)
    at Request.<anonymous> (/app/controllers/ProxyController.js:57:37)
    at Request.emit (node:events:530:35)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1079:12)
    at IncomingMessage.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_HTTP_HEADERS_SENT'
}`

Upgraded and I had the backend crash today. Here is the stack trace.

**Comment by antebrl** [comment]
Thanks alot!
That provides some further insight, which I couldn't get before!

What was the behavior? Did the backend crash? If not, was the stream interrupted?

**Comment by tmess11** [comment]
The stream stopped, so I launched Google Chrome's Dev tools and saw the 502 Error in the console which is usually the error I see with this issue. I checked the backend and it had crashed again with the stack trace above and stopped the container.

**Comment by antebrl** [comment]
Yeah, actually the crash is my bad. The `ERR_HTTP_HEADERS_SENT` occurs because the failure response is sent twice. It's hard to test, because none of my channels have such a behavior. I'll fix it asap and push a commit to main.

At least the initial `ECONNRESET` is caught correctly :)

**Comment by antebrl** [comment]
Ok, so I've pushed a fix for the `ERR_HTTP_HEADERS_SENT` error to the main branch.
I tried to manually replay such an `ECONNRESET` error. The backend didn't crash for me and the stream was also not interrupted.

Still, as I said, its hard to test for me, as I can't replay with your specific circumstances. Thats why, I'd appreciate if you could report back if any more crashes happen. I'll leave the issue open! Thanks alot.

**Comment by tmess11** [comment]
Yeah, all good. I just upgraded and rebuilt. I’ll run it some in the morning and monitor the logs for anything as well. Thanks for the help! I don’t mind testing it out. I’ll report back after a few days of streaming if I have no issue so we can move it to closed or if I see the error without a crash.

**Comment by tmess11** [comment]
Looks like you got it! I think I had the same error today with no backend crash. The stream hangs on the frontend, but that is easy to reload the stream. Maybe in the future you could have it so that the stream auto-reloads when it fails, but that can be thrown deep in the backlog. Thanks for your help on this! I'm looking forward to the future of this program!

**Comment by antebrl** [comment]
You're welcome! 
If stream hangs up or anything else, just reopen this.
